"""Shared application constants."""

# 基础默认值：跨模块共用的时区、语言、存储、平台与推送协议标识。
DEFAULT_TIMEZONE = "Asia/Shanghai"
UTC_TIMEZONE_NAME = "UTC"

DEFAULT_LOCALE = "zh-CN"
DEFAULT_CALENDAR_PROVIDER = "ling"
REDIS_KEY_PREFIX = "ling"
STORAGE_PROVIDER_S3 = "s3"
MCP_EXECUTION_STATUS_PENDING_CLIENT = "pending_client"
PLATFORM_IOS = "ios"
PLATFORM_OHOS = "ohos"
PLATFORM_ALL = "all"
PLATFORM_UNKNOWN = "unknown"
PUSH_TRANSPORT_APNS = "apns"
PUSH_TRANSPORT_HARMONY = "harmony_push"
APNS_PUSH_TYPE_ALERT = "alert"
APNS_PUSH_TYPE_BACKGROUND = "background"
APNS_PRIORITY_ALERT = "10"
APNS_PRIORITY_BACKGROUND = "5"
APNS_ENVIRONMENT_PRODUCTION = "production"
APNS_ENVIRONMENT_DEVELOPMENT = "development"
APNS_ENVIRONMENT_UNKNOWN = "unknown"
HARMONY_PUSH_PROVIDER = "harmony"

APPLE_AUDIENCE_IOS = "top.withling.ling"
# 认证：本地登录与第三方登录 provider，以及短信/邮箱 challenge 生命周期状态。
AUTH_PROVIDER_LOCAL = "local"
AUTH_PROVIDER_APPLE = "apple"
AUTH_PROVIDER_WECHAT = "wechat"
AUTH_CHALLENGE_STATUS_PENDING = "pending"
AUTH_CHALLENGE_STATUS_EXPIRED = "expired"
AUTH_CHALLENGE_STATUS_FAILED = "failed"
AUTH_CHALLENGE_STATUS_VERIFIED = "verified"
USER_STATUS_ACTIVE = "active"
USER_STATUS_DELETED = "deleted"

# 日历来源：Ling 自有日历、系统日历以及第三方同步来源。
CALENDAR_SOURCE_LING = "ling"
CALENDAR_SOURCE_APPLE = "apple"
CALENDAR_SOURCE_FEISHU = "feishu"
CALENDAR_SOURCE_DINGTALK = "dingtalk"
CALENDAR_SOURCE_APPLE_LOCAL = "apple_local"

# 第三方日历连接状态与 Apple 本地日历权限状态。
CALENDAR_CONNECTION_STATUS_NOT_CONNECTED = "not_connected"
CALENDAR_CONNECTION_STATUS_CONNECTED = "connected"
CALENDAR_CONNECTION_STATUS_UNAVAILABLE = "unavailable"
CALENDAR_CONNECTION_STATUS_ACTION_REQUIRED = "action_required"
CALENDAR_CONNECTION_STATUS_SYNCING = "syncing"
CALENDAR_CONNECTION_STATUS_ERROR = "error"
CALENDAR_PERMISSION_GRANTED = "granted"
CALENDAR_PERMISSION_DENIED = "denied"
CALENDAR_PERMISSION_UNSUPPORTED = "unsupported"
CALENDAR_PERMISSION_NOT_DETERMINED = "not_determined"

# Apple 本地日历客户端 mutation 参数：用于前端执行单次/未来重复事件变更。
APPLE_CALENDAR_MUTATION_SPAN_KEY = "span"
APPLE_CALENDAR_MUTATION_THIS_EVENT = "thisEvent"
APPLE_CALENDAR_MUTATION_FUTURE_EVENTS = "futureEvents"
CALENDAR_UPDATE_SCOPE_OCCURRENCE = "occurrence"

# 外部云日历来源集合：用于判断是否需要走第三方同步/清理逻辑。
CALENDAR_EXTERNAL_SOURCES = frozenset(
    {
        CALENDAR_SOURCE_APPLE,
        CALENDAR_SOURCE_FEISHU,
        CALENDAR_SOURCE_DINGTALK,
    }
)

# 已同步事件来源集合：包含 Apple 本地事件和外部云日历事件。
CALENDAR_SYNCED_EVENT_SOURCES = frozenset(
    {
        CALENDAR_SOURCE_APPLE,
        CALENDAR_SOURCE_APPLE_LOCAL,
        CALENDAR_SOURCE_FEISHU,
        CALENDAR_SOURCE_DINGTALK,
    }
)

# 日历事件分类、时间形态与事件状态。
CALENDAR_CATEGORY_PERSONAL = "personal"
CALENDAR_CATEGORY_WORK = "work"
CALENDAR_CATEGORY_MEETING = "meeting"
CALENDAR_CATEGORY_TRAVEL = "travel"
CALENDAR_CATEGORY_HEALTH = "health"
CALENDAR_CATEGORY_FAMILY = "family"
CALENDAR_CATEGORY_OTHER = "other"
CALENDAR_VALID_CATEGORIES = frozenset(
    {
        CALENDAR_CATEGORY_PERSONAL,
        CALENDAR_CATEGORY_WORK,
        CALENDAR_CATEGORY_MEETING,
        CALENDAR_CATEGORY_TRAVEL,
        CALENDAR_CATEGORY_HEALTH,
        CALENDAR_CATEGORY_FAMILY,
        CALENDAR_CATEGORY_OTHER,
    }
)
DEFAULT_CALENDAR_CATEGORY = CALENDAR_CATEGORY_PERSONAL
EXTERNAL_CALENDAR_CATEGORY = "external"
CALENDAR_TIME_SHAPE_SPAN = "span"
CALENDAR_TIME_SHAPE_POINT = "point"
CALENDAR_STATUS_SCHEDULED = "scheduled"
CALENDAR_STATUS_CANCELLED = "cancelled"
CALENDAR_STATUS_CANCELED = "canceled"
CALENDAR_STATUS_DELETED = "deleted"
CALENDAR_STATUS_COMPLETED = "completed"

# 终态事件：不再参与未来提醒、冲突检查等活跃事件逻辑。
CALENDAR_TERMINAL_STATUSES = frozenset(
    {
        CALENDAR_STATUS_CANCELLED,
        CALENDAR_STATUS_CANCELED,
        CALENDAR_STATUS_DELETED,
        CALENDAR_STATUS_COMPLETED,
    }
)

# 删除态事件：来自外部日历同步时用于判断是否下线本地事件。
CALENDAR_DELETED_STATUSES = frozenset(
    {
        CALENDAR_STATUS_CANCELLED,
        CALENDAR_STATUS_CANCELED,
        CALENDAR_STATUS_DELETED,
    }
)

# 日历同步状态与同步结果字段。
CALENDAR_SYNC_STATE_PENDING = "pending"
CALENDAR_SYNC_STATE_LINKED = "linked"
CALENDAR_SYNC_RESULT_KEY_SKIPPED = "skipped"

# 应用内通知：默认分类/优先级与通知投递状态。
DEFAULT_NOTIFICATION_CATEGORY = "general"
NOTIFICATION_CATEGORY_AGENT_COMPLETION = "agent_completion"
DEFAULT_NOTIFICATION_PRIORITY = "normal"
NOTIFICATION_STATUS_QUEUED = "queued"
NOTIFICATION_STATUS_DISPATCHING = "dispatching"
NOTIFICATION_STATUS_SENT = "sent"
NOTIFICATION_STATUS_DELIVERED = "delivered"
NOTIFICATION_STATUS_FAILED = "failed"
NOTIFICATION_STATUS_OPENED = "opened"
NOTIFICATION_STATUS_DISMISSED = "dismissed"
NOTIFICATION_STATUS_EXPIRED = "expired"

# 已被系统接受的通知状态：用于判断 Agent 工具调用是否算成功。
NOTIFICATION_ACCEPTED_STATUSES = frozenset(
    {
        NOTIFICATION_STATUS_SENT,
        NOTIFICATION_STATUS_QUEUED,
        NOTIFICATION_STATUS_DELIVERED,
    }
)

# 近期通知查询默认状态：用于判断是否重复打扰。
NOTIFICATION_RECENT_STATUSES = [
    NOTIFICATION_STATUS_SENT,
    NOTIFICATION_STATUS_QUEUED,
]

# 通知 API 对外允许过滤/返回的状态列表。
NOTIFICATION_API_STATUSES = [
    NOTIFICATION_STATUS_QUEUED,
    NOTIFICATION_STATUS_SENT,
    NOTIFICATION_STATUS_DELIVERED,
    NOTIFICATION_STATUS_OPENED,
    NOTIFICATION_STATUS_DISMISSED,
    NOTIFICATION_STATUS_FAILED,
    NOTIFICATION_STATUS_EXPIRED,
]

# 推送发送结果字段名：PushNotificationService 返回设备发送统计。
PUSH_RESULT_KEY_SUCCESS = "success"
PUSH_RESULT_KEY_FAILED = "failed"
PUSH_RESULT_KEY_SKIPPED = "skipped"

# Agent 运行状态：Redis 活跃 run 标记与消息执行状态。
AGENT_RUN_STATUS_ACTIVE = "active"
AGENT_EXECUTION_STATUS_COMPLETED = "completed"
AGENT_EXECUTION_STATUS_RUNNING = "running"

# 用户反馈：反馈工单的初始状态。
FEEDBACK_STATUS_SUBMITTED = "submitted"

# 会员：套餐层级、访问状态与订阅状态。
MEMBERSHIP_TIER_FREE = "free"
MEMBERSHIP_TIER_PRO = "pro"
MEMBERSHIP_ACCESS_ACTIVE = "active"
MEMBERSHIP_ACCESS_INACTIVE = "inactive"
MEMBERSHIP_STATUS_PENDING = "pending"
MEMBERSHIP_STATUS_ACTIVE = "active"
MEMBERSHIP_STATUS_CANCEL_SCHEDULED = "cancel_scheduled"
MEMBERSHIP_STATUS_PAYMENT_FAILED = "payment_failed"
MEMBERSHIP_STATUS_EXPIRED = "expired"
MEMBERSHIP_STATUS_REVOKED = "revoked"

# 支付：订单/交易/通知状态与交易类型。
PAYMENT_ORDER_STATUS_PAID = "paid"
PAYMENT_TRANSACTION_STATUS_SUCCEEDED = "succeeded"
PAYMENT_TRANSACTION_TYPE_PURCHASE = "purchase"
PAYMENT_TRANSACTION_TYPE_RESTORE = "restore"
PAYMENT_EVENT_TYPE_RENEWAL = "renewal"
PAYMENT_EVENT_TYPE_EXPIRED = "expired"
PAYMENT_EVENT_TYPE_REVOKED = "revoked"
PAYMENT_EVENT_TYPE_REFUND = "refund"
PAYMENT_NOTIFICATION_STATUS_RECEIVED = "received"

# 会员续费类型、支付 provider 与默认币种。
MEMBERSHIP_RENEWAL_RECURRING = "recurring"
MEMBERSHIP_RENEWAL_ONE_TIME = "one_time"
PAYMENT_PROVIDER_APPLE = "apple"
PAYMENT_PROVIDER_ALIPAY = "alipay"
PAYMENT_PROVIDER_WECHAT = "wechat"
DEFAULT_CURRENCY_CODE = "CNY"
